version: '3.7'

services:
  flask:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask